<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.2.0</Version>
        <TargetFramework>netstandard2.0</TargetFramework>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Platforms>x64</Platforms>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DellarteDellaGuerra.Infrastructure.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IsExternalInit" Version="1.0.3" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
        <PackageReference Include="SafeFluentXPath.Implementation" Version="1.0.0" />
        <PackageReference Include="NLog" Version="5.3.4"/>

        <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.0" />

        <PackageReference Include="Harmony.DependencyInjection" Version="0.2.0"/>

        <!--        <Reference Include="Bannerlord.ExpandedTemplate.API">-->
        <!--            <HintPath>$(GameFolder)\Modules\Bannerlord.ExpandedTemplate\Bannerlord.ExpandedTemplate.API\bin\Debug\netstandard2.0\Bannerlord.ExpandedTemplate.API.dll</HintPath>-->
        <!--            <Private>true</Private>-->
        <!--        </Reference>-->

        <ProjectReference Include="..\DellarteDellaGuerra.Domain\DellarteDellaGuerra.Domain.csproj" />
        <ProjectReference Include="..\DellarteDellaGuerra\DellarteDellaGuerra.csproj" />

<!--        <PackageReference Include="Bannerlord.ReferenceAssemblies.Core" Version="$(GameVersion).*-*" PrivateAssets="All" />-->
<!--        <PackageReference Include="Bannerlord.ReferenceAssemblies.Sandbox" Version="$(GameVersion).*-*" PrivateAssets="All" />-->
<!--        <PackageReference Include="Bannerlord.ReferenceAssemblies.Native" Version="$(GameVersion).*-*" PrivateAssets="All" />-->

    </ItemGroup>

    <ItemGroup>
        <Reference Include="$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.*.dll">
            <Private>false</Private>
        </Reference>
        <Reference Include="$(GameFolder)\Modules\SandBox\bin\Win64_Shipping_Client\SandBox*.dll">
            <Private>false</Private>
        </Reference>
        <Reference Include="$(GameFolder)\Modules\Native\bin\Win64_Shipping_Client\*.dll">
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Compile Remove="Cannon\PartyVisualTickSettlementVisualPatch.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="SiegeEngines\cannons.xsd" />
    </ItemGroup>

    <Target Name="Copy Win64 client files to wEditor" AfterTargets="Build">
        <Message Importance="high" Text="Copying files from Win64_Shipping_Client to Win64_Shipping_wEditor..." />
        <ItemGroup>
            <ClientFiles Include="$(MSBuildThisFileDirectory)..\..\bin\Win64_Shipping_Client\**\*" />
        </ItemGroup>
        <Copy
                SourceFiles="@(ClientFiles)"
                DestinationFolder="$(MSBuildThisFileDirectory)..\..\bin\Win64_Shipping_wEditor\%(RecursiveDir)"
                SkipUnchangedFiles="true" />
    </Target>
</Project>
