<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(GameFolder)\..\..\..\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(GameFolder)\..\..\..\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(GameFolder)\..\..\..\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(GameFolder)\..\..\..\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DellarteDellaGuerra\DellarteDellaGuerra.csproj" />
    <ProjectReference Include="..\DellarteDellaGuerra.Domain\DellarteDellaGuerra.Domain.csproj" />
  </ItemGroup>

</Project>
